Add formatting for nested buffers in parameters
stdlib/lib-node pull request #15
Opened 2020-07-08 18:03 UTC by yusuf-musleh

2020-07-08 22:50 UTC, keithwhor commented on lib/parse.js
> +    return b;
The above should be (for the sake of copying data);

return Object.keys(b).reduce(function (obj, key) {
  obj[key] = formatBuffer(b[key]);
  return obj;
}, {});

2020-07-08 22:52 UTC, keithwhor commented on lib/parse.js
Use a triple if statement -- and a final } else { before the last chunk

2020-07-09 01:27 UTC, jacoblee93 requested changes

2020-07-09 01:27 UTC, jacoblee93 commented on lib/request.js
> +      } else if (((res.statusCode / 100) | 0) === 3) {
I would actually set this to only follow 301 or 302 here, other codes have other behavior: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection

2020-07-09 01:27 UTC, jacoblee93 commented on lib/request.js
> +  Object.assign(cfg, {host: parsedUrl.host, path: parsedUrl.pathname, port: parsedUrl.protocol.includes('https') ? 443 : 80});
We do not use `Object.assign` because it's burned us a few times, use a `.reduce` here to combine into a new object

2020-07-09 01:27 UTC, jacoblee93 commented on lib/request.js
> +  cfg.maxRedirects -= 1;
I would pass this as a separate value instead of modifying the config object, the actual "maxRedirects" doesn't change here

2020-07-09 01:27 UTC, jacoblee93 commented on lib/remote.js
> -        return callback(null, response, res.headers);
It looks like we return `res.headers` here too -- we should not change this behavior

2020-07-09 01:27 UTC, jacoblee93 commented on lib/request.js
> +      if (((res.statusCode / 100) | 0) !== 2 && ((res.statusCode / 100) | 0) !== 3) {
I would just check for `!== 3` first here to clean up this if statement

2020-07-09 01:31 UTC, jacoblee93 requested changes

2020-07-09 01:31 UTC, jacoblee93 commented on lib/request.js
> +  } else if (value &&typeof value === 'object') {
Missing space

2020-07-09 01:32 UTC, jacoblee93 requested changes

2020-07-09 01:32 UTC, jacoblee93 commented on lib/request.js
> +  return request(cfg, 'GET', '', {}, Buffer.from(JSON.stringify({})), (err, res) => {
Also, I think the body here should be empty for GET request shouldn't it?

2020-07-09 02:45 UTC, jacoblee93 requested changes

2020-07-09 02:45 UTC, jacoblee93 commented on lib/request.js
> +  let parsedUrl = response.headers.location && url.parse(response.headers.location);
Throw an error if there's no `response.headers.location`

2020-07-09 02:45 UTC, jacoblee93 commented on lib/request.js
> +function followRedirect(cfg, response, maxRedirects, callback) {
Instead of `maxRedirects`, how about `remainingRedirects`?

2020-07-09 02:45 UTC, jacoblee93 commented on lib/request.js
> +      var response = Buffer.concat(buffers);
Want to change all these to `let`?

2020-07-09 02:45 UTC, jacoblee93 commented on lib/request.js
> +  let updatedCfg = Object.keys(cfg).reduce((n, key) => {
How about `redirectCfg` instead of `updatedCfg`

2020-07-09 19:41 UTC, jacoblee93 approved these changes

2020-07-09 19:42 UTC, merged